# debug_me

The script 'add_five.py' is supposed to add five to whatever number you type as a command line argument, like this:

    $ python add_five.py 4
    9

It's broken, though. Instead of "9" you get a horrible error message. See if you can fix it.
